version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - gdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  gdata:
